import Head from 'next/head'
import { Container } from '@material-ui/core';
import HeaderSections from '../src/components/headerSections';
import HeaderBox from '../src/components/headerBox';
import ListShowRepo from '../src/components/listShowRepo';
import stylesHome from '../styles/Home.module.css'

const Home = (props) => {
  const { repo } = props;
  /* Trending */
  return (
    <>
      <Head>
        <title>Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSections>
        <Container maxWidth={'md'} className={stylesHome.fullContForBorder}>
          <HeaderBox pageShow={0} />
          <ListShowRepo data={repo} />
        </Container>
      </HeaderSections>
    </>
  )
}

Home.getInitialProps = async (ctx) => {
  const res = await fetch('https://gh-trending-api.herokuapp.com/repositories')
  const json = await res.json()
  return { repo: json }
}

export default Home